# Generated by Django 5.0.2 on 2024-02-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qr_code_link', models.CharField(max_length=100)),
                ('already_scanned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nb_billets', models.IntegerField()),
                ('billets_vendus', models.IntegerField()),
                ('lien_image', models.CharField(max_length=100)),
                ('lien_video', models.CharField(max_length=100)),
                ('liste_billets', models.ManyToManyField(db_table='event_billets', related_name='events', to='my_api.billet')),
            ],
        ),
        migrations.AddField(
            model_name='billet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='my_api.event'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_organisateur', models.BooleanField(default=False)),
                ('billets', models.ManyToManyField(db_table='user_billets', related_name='users', to='my_api.billet')),
                ('liste_events', models.ManyToManyField(related_name='users', to='my_api.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organised_events', to='my_api.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(db_table='event_participants', related_name='participated_events', to='my_api.user'),
        ),
        migrations.AddField(
            model_name='billet',
            name='telephone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_billets', to='my_api.user'),
        ),
    ]
