# Generated by Django 5.0.2 on 2024-02-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_participant',
            field=models.BooleanField(default=False),
        ),
    ]
