# Generated by Django 5.0.2 on 2024-02-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_user_is_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_participant',
        ),
    ]
