# Generated by Django 5.0.2 on 2024-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0006_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
