# Generated by Django 5.0.2 on 2024-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0008_rename_qr_code_link_billet_qr_code_data_user_two_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
