# Generated by Django 5.0.2 on 2024-03-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0009_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
