# Generated by Django 5.0.2 on 2024-03-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0010_alter_event_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='qr_code_data',
            field=models.TextField(),
        ),
    ]
